### ISSUE TITLE
Failed to find match for field 'ring'.

### ISSUE THREAD

**Issue by Taeyoung96** [bierschi/nclt2ros#1]
@bierschi, Thanks for your great project!  
I use this repository to make NCLT bag files.  
Using this repository, I created a `2013-01-10 bagfile` and execute the [faster-lio](https://github.com/gaoxiang12/faster-lio) algorithm.  

But I got a weird result :cry:  
The trajectory diverges.  
<p align="center"><img src="https://user-images.githubusercontent.com/41863759/167776606-8064bae8-f042-470f-ba5b-cd120ddf0ed0.png" width = "500" ></p>   

The output of the terminal is below.
<p align="center"><img src="https://user-images.githubusercontent.com/41863759/167776961-17d9fc3a-9522-48f7-9479-7e593958c00e.png" width = "700" ></p>   

In [faster-lio](https://github.com/gaoxiang12/faster-lio) repository,  
They provide NCLT dataset [example](https://github.com/gaoxiang12/faster-lio#prepare-the-datasets) in bag file format.  

I execute the same sequence(2013-01-10) and the same [config file](https://github.com/gaoxiang12/faster-lio/blob/main/config/velodyne.yaml) (just change the topic name).  

I got a great result.  
<p align="center"><img src="https://user-images.githubusercontent.com/41863759/167778273-dcbe018b-32a6-424a-9108-bff315f3f863.png" width = "500" ></p>   

The output of the terminal is below.  
<p align="center"><img src="https://user-images.githubusercontent.com/41863759/167778352-f2eb3531-5325-45ca-994c-9540aeac22f1.png" width = "800" ></p>   

I think the difference between two terminals are   
```
failed to find match for field 'time'
failed to find match for field 'ring'
```  

How could I make `ring` and `time` when I make bag file?  
Any idea?  

Thanks,

**Comment by chengwei0427** [comment]
Hi, @Taeyoung96 

Has the problem been solved?

I want to convert a bag with imu, odometry and velodyne, but the velodyne data` failed to find match for field 'time' ,failed to find match for field 'ring'`.

Thanks

**Comment by Taeyoung96** [comment]
@chengwei0427   
Hi, I used another python script to generate bag file.  
In [FAST-LIO](https://github.com/hku-mars/FAST_LIO#42-velodyne-hdl-32e-rosbag), you could use [this script](https://drive.google.com/file/d/1leh7DxbHx29DyS1NJkvEfeNJoccxH7XM/view) and it works fine for me.  

Thanks,

**Comment by chengwei0427** [comment]
Hi， @Taeyoung96 
Thanks for your reply.
I want to test my LIO algorithm with encoder/wheel info, so I need  a bag with odometry info.
Do your have any advice? Or some dataset with encoder/wheel info?

Thanks
